#ifndef __SMT_CFG_H__
#define __SMT_CFG_H__



#include "rtthread.h"
#include "ptcl.h"



//帧结构信息
#define SMTCFG_FRAME_HEAD_DOWN			">TX+CMD"
#define SMTCFG_FRAME_HEAD_UP			">RX+CMD"
#define SMTCFG_FRAME_WRITE				'W'
#define SMTCFG_FRAME_READ				'R'
#define SMTCFG_FRAME_SEPARATOR			'='

//读写标识
#define SMTCFG_TAG_WRITE				0
#define SMTCFG_TAG_READ					0x8000

//page14:内置指令
#define SMTCFG_AFN_GET_DEVICE_INFO				(SMTCFG_TAG_READ	+ (14	<< 8) + 10)		//获取设备信息
#define SMTCFG_AFN_CALIBRATE_TIME				(SMTCFG_TAG_WRITE	+ (14	<< 8) + 30)		//校准时间
#define SMTCFG_AFN_DEBUG_INFO_SWITCH			(SMTCFG_TAG_WRITE	+ (14	<< 8) + 31)		//开关调试信息
#define SMTCFG_AFN_FILE_TO_DEVICE				(SMTCFG_TAG_WRITE	+ (14	<< 8) + 32)		//传输文件到设备
#define SMTCFG_AFN_FILE_FROM_DEVICE				(SMTCFG_TAG_WRITE	+ (14	<< 8) + 33)		//从设备提取

//page0:系统
#define SMTCFG_AFN_RESET_DEVICE					(SMTCFG_TAG_WRITE	+ (0	<< 8) + 0)		//重启设备
#define SMTCFG_AFN_SET_TIME						(SMTCFG_TAG_WRITE	+ (0	<< 8) + 1)		//设置时间
#define SMTCFG_AFN_GET_TIME						(SMTCFG_TAG_READ	+ (0	<< 8) + 1)		//读取时间
#define SMTCFG_AFN_GET_SUPPLY_VOLT				(SMTCFG_TAG_READ	+ (0	<< 8) + 2)		//读取供电电压
#define SMTCFG_AFN_GET_SOFTWARE					(SMTCFG_TAG_READ	+ (0	<< 8) + 3)		//读取软件版本
#define SMTCFG_AFN_CLEAR_OLD_DATA				(SMTCFG_TAG_WRITE	+ (0	<< 8) + 4)		//清除历史数据
#define SMTCFG_AFN_SET_FIRMWARE_URL				(SMTCFG_TAG_WRITE	+ (0	<< 8) + 5)		//设置固件URL
#define SMTCFG_AFN_SET_FATFS_MKFS				(SMTCFG_TAG_WRITE	+ (0	<< 8) + 6)		//格式化文件系统
#define SMTCFG_AFN_SET_FATFS_TEST				(SMTCFG_TAG_WRITE	+ (0	<< 8) + 7)		//测试文件系统
#define SMTCFG_AFN_GET_MEMPOOL_128				(SMTCFG_TAG_READ	+ (0	<< 8) + 8)		//内存池128
#define SMTCFG_AFN_GET_MEMPOOL_256				(SMTCFG_TAG_READ	+ (0	<< 8) + 9)		//内存池256
#define SMTCFG_AFN_GET_MEMPOOL_512				(SMTCFG_TAG_READ	+ (0	<< 8) + 10)		//内存池512
#define SMTCFG_AFN_GET_MEMPOOL_1024				(SMTCFG_TAG_READ	+ (0	<< 8) + 11)		//内存池1024
#define SMTCFG_AFN_GET_MEMPOOL_2048				(SMTCFG_TAG_READ	+ (0	<< 8) + 12)		//内存池2048
#define SMTCFG_AFN_GET_DS18B20_TEMPER			(SMTCFG_TAG_READ	+ (0	<< 8) + 13)		//读取板载温度值
#define SMTCFG_AFN_GET_DS18B20_SN				(SMTCFG_TAG_READ	+ (0	<< 8) + 14)		//读取SN
#define SMTCFG_AFN_SET_FONT_TEST				(SMTCFG_TAG_WRITE	+ (0	<< 8) + 15)		//测试汉字编码

//page8:参数集合信息
#define SMTCFG_AFN_SET_PARAM_SET_DTU			(SMTCFG_TAG_WRITE	+ (8	<< 8) + 0)
#define SMTCFG_AFN_GET_PARAM_SET_DTU			(SMTCFG_TAG_READ	+ (8	<< 8) + 0)
#define SMTCFG_AFN_SET_PARAM_SET_PTCL			(SMTCFG_TAG_WRITE	+ (8	<< 8) + 1)
#define SMTCFG_AFN_GET_PARAM_SET_PTCL			(SMTCFG_TAG_READ	+ (8	<< 8) + 1)
#define SMTCFG_AFN_SET_PARAM_SET_SMT_MANAGE		(SMTCFG_TAG_WRITE	+ (8	<< 8) + 2)
#define SMTCFG_AFN_GET_PARAM_SET_SMT_MANAGE		(SMTCFG_TAG_READ	+ (8	<< 8) + 2)
#define SMTCFG_AFN_SET_PARAM_SET_SAMPLE			(SMTCFG_TAG_WRITE	+ (8	<< 8) + 3)
#define SMTCFG_AFN_GET_PARAM_SET_SAMPLE			(SMTCFG_TAG_READ	+ (8	<< 8) + 3)
#define SMTCFG_AFN_SET_PARAM_SET_ADS1110		(SMTCFG_TAG_WRITE	+ (8	<< 8) + 4)
#define SMTCFG_AFN_GET_PARAM_SET_ADS1110		(SMTCFG_TAG_READ	+ (8	<< 8) + 4)
#define SMTCFG_AFN_SET_PARAM_SET_HJ212			(SMTCFG_TAG_WRITE	+ (8	<< 8) + 5)
#define SMTCFG_AFN_GET_PARAM_SET_HJ212			(SMTCFG_TAG_READ	+ (8	<< 8) + 5)

//page11:调试信息
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_DTU				(SMTCFG_TAG_WRITE	+ (11	<< 8) + 0)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_DTU				(SMTCFG_TAG_READ	+ (11	<< 8) + 0)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_AT				(SMTCFG_TAG_WRITE	+ (11	<< 8) + 1)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_AT				(SMTCFG_TAG_READ	+ (11	<< 8) + 1)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_SAMPLE			(SMTCFG_TAG_WRITE	+ (11	<< 8) + 2)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_SAMPLE			(SMTCFG_TAG_READ	+ (11	<< 8) + 2)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_HTTP				(SMTCFG_TAG_WRITE	+ (11	<< 8) + 3)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_HTTP				(SMTCFG_TAG_READ	+ (11	<< 8) + 3)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_FATFS			(SMTCFG_TAG_WRITE	+ (11	<< 8) + 4)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_FATFS			(SMTCFG_TAG_READ	+ (11	<< 8) + 4)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_BT				(SMTCFG_TAG_WRITE	+ (11	<< 8) + 5)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_BT				(SMTCFG_TAG_READ	+ (11	<< 8) + 5)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_DS18B20			(SMTCFG_TAG_WRITE	+ (11	<< 8) + 6)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_DS18B20			(SMTCFG_TAG_READ	+ (11	<< 8) + 6)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_HJ212			(SMTCFG_TAG_WRITE	+ (11	<< 8) + 7)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_HJ212			(SMTCFG_TAG_READ	+ (11	<< 8) + 7)
#define SMTCFG_AFN_SET_DEBUG_INFO_TYPE_TEST				(SMTCFG_TAG_WRITE	+ (11	<< 8) + 8)
#define SMTCFG_AFN_GET_DEBUG_INFO_TYPE_TEST				(SMTCFG_TAG_READ	+ (11	<< 8) + 8)

//page1:中心站信息
#define SMTCFG_AFN_SET_CA_0						(SMTCFG_TAG_WRITE	+ (1	<< 8) + 0)		//设置中心站0地址
#define SMTCFG_AFN_GET_CA_0						(SMTCFG_TAG_READ	+ (1	<< 8) + 0)		//读取中心站0地址
#define SMTCFG_AFN_SET_PTCL_0					(SMTCFG_TAG_WRITE	+ (1	<< 8) + 10)		//设置中心站0协议
#define SMTCFG_AFN_GET_PTCL_0					(SMTCFG_TAG_READ	+ (1	<< 8) + 10)		//读取中心站0协议
#define SMTCFG_AFN_SET_COMM_FIRST_0				(SMTCFG_TAG_WRITE	+ (1	<< 8) + 20)		//设置中心站0主信道
#define SMTCFG_AFN_GET_COMM_FIRST_0				(SMTCFG_TAG_READ	+ (1	<< 8) + 20)		//读取中心站0主信道
#define SMTCFG_AFN_SET_COMM_SECOND_0			(SMTCFG_TAG_WRITE	+ (1	<< 8) + 30)		//设置中心站0备信道
#define SMTCFG_AFN_GET_COMM_SECOND_0			(SMTCFG_TAG_READ	+ (1	<< 8) + 30)		//读取中心站0备信道
#define SMTCFG_AFN_SET_CA_1						(SMTCFG_TAG_WRITE	+ (1	<< 8) + 1)		//设置中心站1地址
#define SMTCFG_AFN_GET_CA_1						(SMTCFG_TAG_READ	+ (1	<< 8) + 1)		//读取中心站1地址
#define SMTCFG_AFN_SET_PTCL_1					(SMTCFG_TAG_WRITE	+ (1	<< 8) + 11)		//设置中心站1协议
#define SMTCFG_AFN_GET_PTCL_1					(SMTCFG_TAG_READ	+ (1	<< 8) + 11)		//读取中心站1协议
#define SMTCFG_AFN_SET_COMM_FIRST_1				(SMTCFG_TAG_WRITE	+ (1	<< 8) + 21)		//设置中心站1主信道
#define SMTCFG_AFN_GET_COMM_FIRST_1				(SMTCFG_TAG_READ	+ (1	<< 8) + 21)		//读取中心站1主信道
#define SMTCFG_AFN_SET_COMM_SECOND_1			(SMTCFG_TAG_WRITE	+ (1	<< 8) + 31)		//设置中心站1备信道
#define SMTCFG_AFN_GET_COMM_SECOND_1			(SMTCFG_TAG_READ	+ (1	<< 8) + 31)		//读取中心站1备信道
#define SMTCFG_AFN_SET_CA_2						(SMTCFG_TAG_WRITE	+ (1	<< 8) + 2)		//设置中心站2地址
#define SMTCFG_AFN_GET_CA_2						(SMTCFG_TAG_READ	+ (1	<< 8) + 2)		//读取中心站2地址
#define SMTCFG_AFN_SET_PTCL_2					(SMTCFG_TAG_WRITE	+ (1	<< 8) + 12)		//设置中心站2协议
#define SMTCFG_AFN_GET_PTCL_2					(SMTCFG_TAG_READ	+ (1	<< 8) + 12)		//读取中心站2协议
#define SMTCFG_AFN_SET_COMM_FIRST_2				(SMTCFG_TAG_WRITE	+ (1	<< 8) + 22)		//设置中心站2主信道
#define SMTCFG_AFN_GET_COMM_FIRST_2				(SMTCFG_TAG_READ	+ (1	<< 8) + 22)		//读取中心站2主信道
#define SMTCFG_AFN_SET_COMM_SECOND_2			(SMTCFG_TAG_WRITE	+ (1	<< 8) + 32)		//设置中心站2备信道
#define SMTCFG_AFN_GET_COMM_SECOND_2			(SMTCFG_TAG_READ	+ (1	<< 8) + 32)		//读取中心站2备信道
#define SMTCFG_AFN_SET_CA_3						(SMTCFG_TAG_WRITE	+ (1	<< 8) + 3)		//设置中心站3地址
#define SMTCFG_AFN_GET_CA_3						(SMTCFG_TAG_READ	+ (1	<< 8) + 3)		//读取中心站3地址
#define SMTCFG_AFN_SET_PTCL_3					(SMTCFG_TAG_WRITE	+ (1	<< 8) + 13)		//设置中心站3协议
#define SMTCFG_AFN_GET_PTCL_3					(SMTCFG_TAG_READ	+ (1	<< 8) + 13)		//读取中心站3协议
#define SMTCFG_AFN_SET_COMM_FIRST_3				(SMTCFG_TAG_WRITE	+ (1	<< 8) + 23)		//设置中心站3主信道
#define SMTCFG_AFN_GET_COMM_FIRST_3				(SMTCFG_TAG_READ	+ (1	<< 8) + 23)		//读取中心站3主信道
#define SMTCFG_AFN_SET_COMM_SECOND_3			(SMTCFG_TAG_WRITE	+ (1	<< 8) + 33)		//设置中心站3备信道
#define SMTCFG_AFN_GET_COMM_SECOND_3			(SMTCFG_TAG_READ	+ (1	<< 8) + 33)		//读取中心站3备信道

//page2:dtu配置
#define SMTCFG_AFN_SET_DTU_APN					(SMTCFG_TAG_WRITE	+ (2	<< 8) + 1)		//设置dtu接入点
#define SMTCFG_AFN_GET_DTU_APN					(SMTCFG_TAG_READ	+ (2	<< 8) + 1)		//读取dtu接入点
#define SMTCFG_AFN_GET_DTU_RSSI					(SMTCFG_TAG_READ	+ (2	<< 8) + 2)		//读取信号强度
#define SMTCFG_AFN_DIAL_PHONE					(SMTCFG_TAG_WRITE	+ (2	<< 8) + 3)		//拨打电话
#define SMTCFG_AFN_ADD_PREVILIGE_PHONE			(SMTCFG_TAG_WRITE	+ (2	<< 8) + 4)		//添加管理号
#define SMTCFG_AFN_QUERY_PREVILIGE_PHONE		(SMTCFG_TAG_READ	+ (2	<< 8) + 4)		//查询管理号
#define SMTCFG_AFN_ADD_SUPER_PHONE				(SMTCFG_TAG_WRITE	+ (2	<< 8) + 5)		//添加授权号
#define SMTCFG_AFN_QUERY_SUPER_PHONE			(SMTCFG_TAG_READ	+ (2	<< 8) + 5)		//查询授权号
#define SMTCFG_AFN_DEL_SUPER_PHONE				(SMTCFG_TAG_WRITE	+ (2	<< 8) + 6)		//删除号码

//page3:dtu通道0
#define SMTCFG_AFN_SET_IPCH_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 10)		//设置ip0通道
#define SMTCFG_AFN_GET_IPCH_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 10)		//读取ip0通道
#define SMTCFG_AFN_SET_IPADDR_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 11)		//设置ip0地址
#define SMTCFG_AFN_GET_IPADDR_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 11)		//读取ip0地址
#define SMTCFG_AFN_SET_IPTYPE_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 12)		//设置ip0协议类型
#define SMTCFG_AFN_GET_IPTYPE_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 12)		//读取ip0协议类型
#define SMTCFG_AFN_SET_SMSCH_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 13)		//设置sms0通道
#define SMTCFG_AFN_GET_SMSCH_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 13)		//读取sms0通道
#define SMTCFG_AFN_SET_SMSADDR_0				(SMTCFG_TAG_WRITE	+ (3	<< 8) + 14)		//设置sms0地址
#define SMTCFG_AFN_GET_SMSADDR_0				(SMTCFG_TAG_READ	+ (3	<< 8) + 14)		//读取sms0地址
#define SMTCFG_AFN_SET_MODE_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 15)		//设置模式
#define SMTCFG_AFN_GET_MODE_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 15)		//读取模式
#define SMTCFG_AFN_SET_HEART_0					(SMTCFG_TAG_WRITE	+ (3	<< 8) + 16)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_0					(SMTCFG_TAG_READ	+ (3	<< 8) + 16)		//读取心跳间隔
#define SMTCFG_AFN_SET_IMMEDIATELY_0			(SMTCFG_TAG_WRITE	+ (3	<< 8) + 17)

//page4:dtu通道1
#define SMTCFG_AFN_SET_IPCH_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 10)		//设置ip1通道
#define SMTCFG_AFN_GET_IPCH_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 10)		//读取ip1通道
#define SMTCFG_AFN_SET_IPADDR_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 11)		//设置ip1地址
#define SMTCFG_AFN_GET_IPADDR_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 11)		//读取ip1地址
#define SMTCFG_AFN_SET_IPTYPE_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 12)		//设置ip1协议类型
#define SMTCFG_AFN_GET_IPTYPE_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 12)		//读取ip1协议类型
#define SMTCFG_AFN_SET_SMSCH_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 13)		//设置sms1通道
#define SMTCFG_AFN_GET_SMSCH_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 13)		//读取sms1通道
#define SMTCFG_AFN_SET_SMSADDR_1				(SMTCFG_TAG_WRITE	+ (4	<< 8) + 14)		//设置sms1地址
#define SMTCFG_AFN_GET_SMSADDR_1				(SMTCFG_TAG_READ	+ (4	<< 8) + 14)		//读取sms1地址
#define SMTCFG_AFN_SET_MODE_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 15)		//设置模式
#define SMTCFG_AFN_GET_MODE_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 15)		//读取模式
#define SMTCFG_AFN_SET_HEART_1					(SMTCFG_TAG_WRITE	+ (4	<< 8) + 16)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_1					(SMTCFG_TAG_READ	+ (4	<< 8) + 16)		//读取心跳间隔
#define SMTCFG_AFN_SET_IMMEDIATELY_1			(SMTCFG_TAG_WRITE	+ (4	<< 8) + 17)

//page5:dtu通道2
#define SMTCFG_AFN_SET_IPCH_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 10)		//设置ip2通道
#define SMTCFG_AFN_GET_IPCH_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 10)		//读取ip2通道
#define SMTCFG_AFN_SET_IPADDR_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 11)		//设置ip2地址
#define SMTCFG_AFN_GET_IPADDR_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 11)		//读取ip2地址
#define SMTCFG_AFN_SET_IPTYPE_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 12)		//设置ip2协议类型
#define SMTCFG_AFN_GET_IPTYPE_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 12)		//读取ip2协议类型
#define SMTCFG_AFN_SET_SMSCH_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 13)		//设置sms2通道
#define SMTCFG_AFN_GET_SMSCH_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 13)		//读取sms2通道
#define SMTCFG_AFN_SET_SMSADDR_2				(SMTCFG_TAG_WRITE	+ (5	<< 8) + 14)		//设置sms2地址
#define SMTCFG_AFN_GET_SMSADDR_2				(SMTCFG_TAG_READ	+ (5	<< 8) + 14)		//读取sms2地址
#define SMTCFG_AFN_SET_MODE_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 15)		//设置模式
#define SMTCFG_AFN_GET_MODE_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 15)		//读取模式
#define SMTCFG_AFN_SET_HEART_2					(SMTCFG_TAG_WRITE	+ (5	<< 8) + 16)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_2					(SMTCFG_TAG_READ	+ (5	<< 8) + 16)		//读取心跳间隔
#define SMTCFG_AFN_SET_IMMEDIATELY_2			(SMTCFG_TAG_WRITE	+ (5	<< 8) + 17)

//page6:dtu通道3
#define SMTCFG_AFN_SET_IPCH_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 10)		//设置ip3通道
#define SMTCFG_AFN_GET_IPCH_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 10)		//读取ip3通道
#define SMTCFG_AFN_SET_IPADDR_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 11)		//设置ip3地址
#define SMTCFG_AFN_GET_IPADDR_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 11)		//读取ip3地址
#define SMTCFG_AFN_SET_IPTYPE_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 12)		//设置ip3协议类型
#define SMTCFG_AFN_GET_IPTYPE_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 12)		//读取ip3协议类型
#define SMTCFG_AFN_SET_SMSCH_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 13)		//设置sms3通道
#define SMTCFG_AFN_GET_SMSCH_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 13)		//读取sms3通道
#define SMTCFG_AFN_SET_SMSADDR_3				(SMTCFG_TAG_WRITE	+ (6	<< 8) + 14)		//设置sms3地址
#define SMTCFG_AFN_GET_SMSADDR_3				(SMTCFG_TAG_READ	+ (6	<< 8) + 14)		//读取sms3地址
#define SMTCFG_AFN_SET_MODE_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 15)		//设置模式
#define SMTCFG_AFN_GET_MODE_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 15)		//读取模式
#define SMTCFG_AFN_SET_HEART_3					(SMTCFG_TAG_WRITE	+ (6	<< 8) + 16)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_3					(SMTCFG_TAG_READ	+ (6	<< 8) + 16)		//读取心跳间隔
#define SMTCFG_AFN_SET_IMMEDIATELY_3			(SMTCFG_TAG_WRITE	+ (6	<< 8) + 17)

//page7:设备管理平台
#define SMTCFG_AFN_SET_IPCH_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 10)		//设置ip4通道
#define SMTCFG_AFN_GET_IPCH_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 10)		//读取ip4通道
#define SMTCFG_AFN_SET_IPADDR_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 11)		//设置ip4地址
#define SMTCFG_AFN_GET_IPADDR_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 11)		//读取ip4地址
#define SMTCFG_AFN_SET_IPTYPE_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 12)		//设置ip4协议类型
#define SMTCFG_AFN_GET_IPTYPE_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 12)		//读取ip4协议类型
#define SMTCFG_AFN_SET_SMSCH_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 13)		//设置sms4通道
#define SMTCFG_AFN_GET_SMSCH_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 13)		//读取sms4通道
#define SMTCFG_AFN_SET_SMSADDR_4				(SMTCFG_TAG_WRITE	+ (7	<< 8) + 14)		//设置sms4地址
#define SMTCFG_AFN_GET_SMSADDR_4				(SMTCFG_TAG_READ	+ (7	<< 8) + 14)		//读取sms4地址
#define SMTCFG_AFN_SET_MODE_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 15)		//设置模式
#define SMTCFG_AFN_GET_MODE_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 15)		//读取模式
#define SMTCFG_AFN_SET_HEART_4					(SMTCFG_TAG_WRITE	+ (7	<< 8) + 16)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_4					(SMTCFG_TAG_READ	+ (7	<< 8) + 16)		//读取心跳间隔
#define SMTCFG_AFN_SET_STA_PERIOD				(SMTCFG_TAG_WRITE	+ (7	<< 8) + 17)		//设置状态上报间隔
#define SMTCFG_AFN_GET_STA_PERIOD				(SMTCFG_TAG_READ	+ (7	<< 8) + 17)		//读取状态上报间隔
#define SMTCFG_AFN_SET_TIMING_PERIOD			(SMTCFG_TAG_WRITE	+ (7	<< 8) + 18)		//设置校时间隔
#define SMTCFG_AFN_GET_TIMING_PERIOD			(SMTCFG_TAG_READ	+ (7	<< 8) + 18)		//读取校时间隔
#define SMTCFG_AFN_SET_HEART_PERIOD				(SMTCFG_TAG_WRITE	+ (7	<< 8) + 19)		//设置心跳间隔
#define SMTCFG_AFN_GET_HEART_PERIOD				(SMTCFG_TAG_READ	+ (7	<< 8) + 19)		//读取心跳间隔
#define SMTCFG_AFN_SET_IMMEDIATELY_4			(SMTCFG_TAG_WRITE	+ (7	<< 8) + 20)

//page10:蓝牙
#define SMTCFG_AFN_SET_BT_MODULE_NAME			(SMTCFG_TAG_WRITE	+ (10	<< 8) + 0)		//模块名称
#define SMTCFG_AFN_GET_BT_MODULE_NAME			(SMTCFG_TAG_READ	+ (10	<< 8) + 0)
#define SMTCFG_AFN_GET_BT_SOFT_VER				(SMTCFG_TAG_READ	+ (10	<< 8) + 1)		//软件版本
#define SMTCFG_AFN_SET_BT_TX_ENERGY				(SMTCFG_TAG_WRITE	+ (10	<< 8) + 2)		//发射功率
#define SMTCFG_AFN_GET_BT_TX_ENERGY				(SMTCFG_TAG_READ	+ (10	<< 8) + 2)
#define SMTCFG_AFN_SET_BT_RX_AMP				(SMTCFG_TAG_WRITE	+ (10	<< 8) + 3)		//接收增益
#define SMTCFG_AFN_GET_BT_RX_AMP				(SMTCFG_TAG_READ	+ (10	<< 8) + 3)
#define SMTCFG_AFN_SET_BT_ADV_INTERVAL			(SMTCFG_TAG_WRITE	+ (10	<< 8) + 4)		//广播间隔
#define SMTCFG_AFN_GET_BT_ADV_INTERVAL			(SMTCFG_TAG_READ	+ (10	<< 8) + 4)
#define SMTCFG_AFN_SET_BT_CON_INTERVAL			(SMTCFG_TAG_WRITE	+ (10	<< 8) + 5)		//连接间隔
#define SMTCFG_AFN_GET_BT_CON_INTERVAL			(SMTCFG_TAG_READ	+ (10	<< 8) + 5)
#define SMTCFG_AFN_SET_BT_ADV_STA				(SMTCFG_TAG_WRITE	+ (10	<< 8) + 6)		//广播开关
#define SMTCFG_AFN_GET_BT_ADV_STA				(SMTCFG_TAG_READ	+ (10	<< 8) + 6)

//page17:sample0
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_0				(SMTCFG_TAG_WRITE	+ (17	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_0				(SMTCFG_TAG_READ	+ (17	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_0				(SMTCFG_TAG_WRITE	+ (17	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_0				(SMTCFG_TAG_READ	+ (17	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_0					(SMTCFG_TAG_WRITE	+ (17	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_0					(SMTCFG_TAG_READ	+ (17	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_0				(SMTCFG_TAG_WRITE	+ (17	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_0				(SMTCFG_TAG_READ	+ (17	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_0					(SMTCFG_TAG_WRITE	+ (17	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_0					(SMTCFG_TAG_READ	+ (17	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_0			(SMTCFG_TAG_WRITE	+ (17	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_0			(SMTCFG_TAG_READ	+ (17	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_0						(SMTCFG_TAG_WRITE	+ (17	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_0						(SMTCFG_TAG_READ	+ (17	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_0						(SMTCFG_TAG_WRITE	+ (17	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_0						(SMTCFG_TAG_READ	+ (17	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_0					(SMTCFG_TAG_WRITE	+ (17	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_0					(SMTCFG_TAG_READ	+ (17	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_0					(SMTCFG_TAG_WRITE	+ (17	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_0					(SMTCFG_TAG_READ	+ (17	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_0						(SMTCFG_TAG_WRITE	+ (17	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_0						(SMTCFG_TAG_READ	+ (17	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_0					(SMTCFG_TAG_WRITE	+ (17	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_0					(SMTCFG_TAG_READ	+ (17	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_0				(SMTCFG_TAG_WRITE	+ (17	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_0				(SMTCFG_TAG_READ	+ (17	<< 8) + 12)

//page18:sample1
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_1				(SMTCFG_TAG_WRITE	+ (18	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_1				(SMTCFG_TAG_READ	+ (18	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_1				(SMTCFG_TAG_WRITE	+ (18	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_1				(SMTCFG_TAG_READ	+ (18	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_1					(SMTCFG_TAG_WRITE	+ (18	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_1					(SMTCFG_TAG_READ	+ (18	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_1				(SMTCFG_TAG_WRITE	+ (18	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_1				(SMTCFG_TAG_READ	+ (18	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_1					(SMTCFG_TAG_WRITE	+ (18	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_1					(SMTCFG_TAG_READ	+ (18	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_1			(SMTCFG_TAG_WRITE	+ (18	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_1			(SMTCFG_TAG_READ	+ (18	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_1						(SMTCFG_TAG_WRITE	+ (18	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_1						(SMTCFG_TAG_READ	+ (18	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_1						(SMTCFG_TAG_WRITE	+ (18	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_1						(SMTCFG_TAG_READ	+ (18	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_1					(SMTCFG_TAG_WRITE	+ (18	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_1					(SMTCFG_TAG_READ	+ (18	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_1					(SMTCFG_TAG_WRITE	+ (18	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_1					(SMTCFG_TAG_READ	+ (18	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_1						(SMTCFG_TAG_WRITE	+ (18	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_1						(SMTCFG_TAG_READ	+ (18	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_1					(SMTCFG_TAG_WRITE	+ (18	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_1					(SMTCFG_TAG_READ	+ (18	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_1				(SMTCFG_TAG_WRITE	+ (18	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_1				(SMTCFG_TAG_READ	+ (18	<< 8) + 12)

//page19:sample2
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_2				(SMTCFG_TAG_WRITE	+ (19	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_2				(SMTCFG_TAG_READ	+ (19	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_2				(SMTCFG_TAG_WRITE	+ (19	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_2				(SMTCFG_TAG_READ	+ (19	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_2					(SMTCFG_TAG_WRITE	+ (19	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_2					(SMTCFG_TAG_READ	+ (19	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_2				(SMTCFG_TAG_WRITE	+ (19	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_2				(SMTCFG_TAG_READ	+ (19	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_2					(SMTCFG_TAG_WRITE	+ (19	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_2					(SMTCFG_TAG_READ	+ (19	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_2			(SMTCFG_TAG_WRITE	+ (19	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_2			(SMTCFG_TAG_READ	+ (19	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_2						(SMTCFG_TAG_WRITE	+ (19	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_2						(SMTCFG_TAG_READ	+ (19	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_2						(SMTCFG_TAG_WRITE	+ (19	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_2						(SMTCFG_TAG_READ	+ (19	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_2					(SMTCFG_TAG_WRITE	+ (19	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_2					(SMTCFG_TAG_READ	+ (19	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_2					(SMTCFG_TAG_WRITE	+ (19	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_2					(SMTCFG_TAG_READ	+ (19	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_2						(SMTCFG_TAG_WRITE	+ (19	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_2						(SMTCFG_TAG_READ	+ (19	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_2					(SMTCFG_TAG_WRITE	+ (19	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_2					(SMTCFG_TAG_READ	+ (19	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_2				(SMTCFG_TAG_WRITE	+ (19	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_2				(SMTCFG_TAG_READ	+ (19	<< 8) + 12)

//page20:sample3
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_3				(SMTCFG_TAG_WRITE	+ (20	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_3				(SMTCFG_TAG_READ	+ (20	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_3				(SMTCFG_TAG_WRITE	+ (20	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_3				(SMTCFG_TAG_READ	+ (20	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_3					(SMTCFG_TAG_WRITE	+ (20	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_3					(SMTCFG_TAG_READ	+ (20	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_3				(SMTCFG_TAG_WRITE	+ (20	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_3				(SMTCFG_TAG_READ	+ (20	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_3					(SMTCFG_TAG_WRITE	+ (20	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_3					(SMTCFG_TAG_READ	+ (20	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_3			(SMTCFG_TAG_WRITE	+ (20	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_3			(SMTCFG_TAG_READ	+ (20	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_3						(SMTCFG_TAG_WRITE	+ (20	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_3						(SMTCFG_TAG_READ	+ (20	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_3						(SMTCFG_TAG_WRITE	+ (20	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_3						(SMTCFG_TAG_READ	+ (20	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_3					(SMTCFG_TAG_WRITE	+ (20	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_3					(SMTCFG_TAG_READ	+ (20	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_3					(SMTCFG_TAG_WRITE	+ (20	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_3					(SMTCFG_TAG_READ	+ (20	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_3						(SMTCFG_TAG_WRITE	+ (20	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_3						(SMTCFG_TAG_READ	+ (20	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_3					(SMTCFG_TAG_WRITE	+ (20	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_3					(SMTCFG_TAG_READ	+ (20	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_3				(SMTCFG_TAG_WRITE	+ (20	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_3				(SMTCFG_TAG_READ	+ (20	<< 8) + 12)

//page21:sample4
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_4				(SMTCFG_TAG_WRITE	+ (21	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_4				(SMTCFG_TAG_READ	+ (21	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_4				(SMTCFG_TAG_WRITE	+ (21	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_4				(SMTCFG_TAG_READ	+ (21	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_4					(SMTCFG_TAG_WRITE	+ (21	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_4					(SMTCFG_TAG_READ	+ (21	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_4				(SMTCFG_TAG_WRITE	+ (21	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_4				(SMTCFG_TAG_READ	+ (21	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_4					(SMTCFG_TAG_WRITE	+ (21	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_4					(SMTCFG_TAG_READ	+ (21	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_4			(SMTCFG_TAG_WRITE	+ (21	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_4			(SMTCFG_TAG_READ	+ (21	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_4						(SMTCFG_TAG_WRITE	+ (21	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_4						(SMTCFG_TAG_READ	+ (21	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_4						(SMTCFG_TAG_WRITE	+ (21	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_4						(SMTCFG_TAG_READ	+ (21	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_4					(SMTCFG_TAG_WRITE	+ (21	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_4					(SMTCFG_TAG_READ	+ (21	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_4					(SMTCFG_TAG_WRITE	+ (21	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_4					(SMTCFG_TAG_READ	+ (21	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_4						(SMTCFG_TAG_WRITE	+ (21	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_4						(SMTCFG_TAG_READ	+ (21	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_4					(SMTCFG_TAG_WRITE	+ (21	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_4					(SMTCFG_TAG_READ	+ (21	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_4				(SMTCFG_TAG_WRITE	+ (21	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_4				(SMTCFG_TAG_READ	+ (21	<< 8) + 12)

//page22:sample5
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_5				(SMTCFG_TAG_WRITE	+ (22	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_5				(SMTCFG_TAG_READ	+ (22	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_5				(SMTCFG_TAG_WRITE	+ (22	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_5				(SMTCFG_TAG_READ	+ (22	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_5					(SMTCFG_TAG_WRITE	+ (22	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_5					(SMTCFG_TAG_READ	+ (22	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_5				(SMTCFG_TAG_WRITE	+ (22	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_5				(SMTCFG_TAG_READ	+ (22	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_5					(SMTCFG_TAG_WRITE	+ (22	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_5					(SMTCFG_TAG_READ	+ (22	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_5			(SMTCFG_TAG_WRITE	+ (22	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_5			(SMTCFG_TAG_READ	+ (22	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_5						(SMTCFG_TAG_WRITE	+ (22	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_5						(SMTCFG_TAG_READ	+ (22	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_5						(SMTCFG_TAG_WRITE	+ (22	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_5						(SMTCFG_TAG_READ	+ (22	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_5					(SMTCFG_TAG_WRITE	+ (22	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_5					(SMTCFG_TAG_READ	+ (22	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_5					(SMTCFG_TAG_WRITE	+ (22	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_5					(SMTCFG_TAG_READ	+ (22	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_5						(SMTCFG_TAG_WRITE	+ (22	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_5						(SMTCFG_TAG_READ	+ (22	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_5					(SMTCFG_TAG_WRITE	+ (22	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_5					(SMTCFG_TAG_READ	+ (22	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_5				(SMTCFG_TAG_WRITE	+ (22	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_5				(SMTCFG_TAG_READ	+ (22	<< 8) + 12)

//page23:sample6
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_6				(SMTCFG_TAG_WRITE	+ (23	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_6				(SMTCFG_TAG_READ	+ (23	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_6				(SMTCFG_TAG_WRITE	+ (23	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_6				(SMTCFG_TAG_READ	+ (23	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_6					(SMTCFG_TAG_WRITE	+ (23	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_6					(SMTCFG_TAG_READ	+ (23	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_6				(SMTCFG_TAG_WRITE	+ (23	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_6				(SMTCFG_TAG_READ	+ (23	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_6					(SMTCFG_TAG_WRITE	+ (23	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_6					(SMTCFG_TAG_READ	+ (23	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_6			(SMTCFG_TAG_WRITE	+ (23	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_6			(SMTCFG_TAG_READ	+ (23	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_6						(SMTCFG_TAG_WRITE	+ (23	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_6						(SMTCFG_TAG_READ	+ (23	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_6						(SMTCFG_TAG_WRITE	+ (23	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_6						(SMTCFG_TAG_READ	+ (23	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_6					(SMTCFG_TAG_WRITE	+ (23	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_6					(SMTCFG_TAG_READ	+ (23	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_6					(SMTCFG_TAG_WRITE	+ (23	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_6					(SMTCFG_TAG_READ	+ (23	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_6						(SMTCFG_TAG_WRITE	+ (23	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_6						(SMTCFG_TAG_READ	+ (23	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_6					(SMTCFG_TAG_WRITE	+ (23	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_6					(SMTCFG_TAG_READ	+ (23	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_6				(SMTCFG_TAG_WRITE	+ (23	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_6				(SMTCFG_TAG_READ	+ (23	<< 8) + 12)

//page24:sample7
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_7				(SMTCFG_TAG_WRITE	+ (24	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_7				(SMTCFG_TAG_READ	+ (24	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_7				(SMTCFG_TAG_WRITE	+ (24	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_7				(SMTCFG_TAG_READ	+ (24	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_7					(SMTCFG_TAG_WRITE	+ (24	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_7					(SMTCFG_TAG_READ	+ (24	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_7				(SMTCFG_TAG_WRITE	+ (24	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_7				(SMTCFG_TAG_READ	+ (24	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_7					(SMTCFG_TAG_WRITE	+ (24	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_7					(SMTCFG_TAG_READ	+ (24	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_7			(SMTCFG_TAG_WRITE	+ (24	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_7			(SMTCFG_TAG_READ	+ (24	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_7						(SMTCFG_TAG_WRITE	+ (24	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_7						(SMTCFG_TAG_READ	+ (24	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_7						(SMTCFG_TAG_WRITE	+ (24	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_7						(SMTCFG_TAG_READ	+ (24	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_7					(SMTCFG_TAG_WRITE	+ (24	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_7					(SMTCFG_TAG_READ	+ (24	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_7					(SMTCFG_TAG_WRITE	+ (24	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_7					(SMTCFG_TAG_READ	+ (24	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_7						(SMTCFG_TAG_WRITE	+ (24	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_7						(SMTCFG_TAG_READ	+ (24	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_7					(SMTCFG_TAG_WRITE	+ (24	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_7					(SMTCFG_TAG_READ	+ (24	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_7				(SMTCFG_TAG_WRITE	+ (24	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_7				(SMTCFG_TAG_READ	+ (24	<< 8) + 12)

//page25:sample8
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_8				(SMTCFG_TAG_WRITE	+ (25	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_8				(SMTCFG_TAG_READ	+ (25	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_8				(SMTCFG_TAG_WRITE	+ (25	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_8				(SMTCFG_TAG_READ	+ (25	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_8					(SMTCFG_TAG_WRITE	+ (25	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_8					(SMTCFG_TAG_READ	+ (25	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_8				(SMTCFG_TAG_WRITE	+ (25	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_8				(SMTCFG_TAG_READ	+ (25	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_8					(SMTCFG_TAG_WRITE	+ (25	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_8					(SMTCFG_TAG_READ	+ (25	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_8			(SMTCFG_TAG_WRITE	+ (25	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_8			(SMTCFG_TAG_READ	+ (25	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_8						(SMTCFG_TAG_WRITE	+ (25	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_8						(SMTCFG_TAG_READ	+ (25	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_8						(SMTCFG_TAG_WRITE	+ (25	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_8						(SMTCFG_TAG_READ	+ (25	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_8					(SMTCFG_TAG_WRITE	+ (25	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_8					(SMTCFG_TAG_READ	+ (25	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_8					(SMTCFG_TAG_WRITE	+ (25	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_8					(SMTCFG_TAG_READ	+ (25	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_8						(SMTCFG_TAG_WRITE	+ (25	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_8						(SMTCFG_TAG_READ	+ (25	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_8					(SMTCFG_TAG_WRITE	+ (25	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_8					(SMTCFG_TAG_READ	+ (25	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_8				(SMTCFG_TAG_WRITE	+ (25	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_8				(SMTCFG_TAG_READ	+ (25	<< 8) + 12)

//page26:sample9
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_TYPE_9				(SMTCFG_TAG_WRITE	+ (26	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_TYPE_9				(SMTCFG_TAG_READ	+ (26	<< 8) + 0)
#define SMTCFG_AFN_SET_SAMPLE_SENSOR_ADDR_9				(SMTCFG_TAG_WRITE	+ (26	<< 8) + 1)
#define SMTCFG_AFN_GET_SAMPLE_SENSOR_ADDR_9				(SMTCFG_TAG_READ	+ (26	<< 8) + 1)
#define SMTCFG_AFN_SET_SAMPLE_HW_PORT_9					(SMTCFG_TAG_WRITE	+ (26	<< 8) + 2)
#define SMTCFG_AFN_GET_SAMPLE_HW_PORT_9					(SMTCFG_TAG_READ	+ (26	<< 8) + 2)
#define SMTCFG_AFN_SET_SAMPLE_PROTOCOL_9				(SMTCFG_TAG_WRITE	+ (26	<< 8) + 3)
#define SMTCFG_AFN_GET_SAMPLE_PROTOCOL_9				(SMTCFG_TAG_READ	+ (26	<< 8) + 3)
#define SMTCFG_AFN_SET_SAMPLE_HW_RATE_9					(SMTCFG_TAG_WRITE	+ (26	<< 8) + 4)
#define SMTCFG_AFN_GET_SAMPLE_HW_RATE_9					(SMTCFG_TAG_READ	+ (26	<< 8) + 4)
#define SMTCFG_AFN_SET_SAMPLE_STORE_PERIOD_9			(SMTCFG_TAG_WRITE	+ (26	<< 8) + 5)
#define SMTCFG_AFN_GET_SAMPLE_STORE_PERIOD_9			(SMTCFG_TAG_READ	+ (26	<< 8) + 5)
#define SMTCFG_AFN_SET_SAMPLE_K_9						(SMTCFG_TAG_WRITE	+ (26	<< 8) + 6)
#define SMTCFG_AFN_GET_SAMPLE_K_9						(SMTCFG_TAG_READ	+ (26	<< 8) + 6)
#define SMTCFG_AFN_SET_SAMPLE_B_9						(SMTCFG_TAG_WRITE	+ (26	<< 8) + 7)
#define SMTCFG_AFN_GET_SAMPLE_B_9						(SMTCFG_TAG_READ	+ (26	<< 8) + 7)
#define SMTCFG_AFN_SET_SAMPLE_BASE_9					(SMTCFG_TAG_WRITE	+ (26	<< 8) + 8)
#define SMTCFG_AFN_GET_SAMPLE_BASE_9					(SMTCFG_TAG_READ	+ (26	<< 8) + 8)
#define SMTCFG_AFN_SET_SAMPLE_OFFSET_9					(SMTCFG_TAG_WRITE	+ (26	<< 8) + 9)
#define SMTCFG_AFN_GET_SAMPLE_OFFSET_9					(SMTCFG_TAG_READ	+ (26	<< 8) + 9)
#define SMTCFG_AFN_SET_SAMPLE_UP_9						(SMTCFG_TAG_WRITE	+ (26	<< 8) + 10)
#define SMTCFG_AFN_GET_SAMPLE_UP_9						(SMTCFG_TAG_READ	+ (26	<< 8) + 10)
#define SMTCFG_AFN_SET_SAMPLE_DOWN_9					(SMTCFG_TAG_WRITE	+ (26	<< 8) + 11)
#define SMTCFG_AFN_GET_SAMPLE_DOWN_9					(SMTCFG_TAG_READ	+ (26	<< 8) + 11)
#define SMTCFG_AFN_SET_SAMPLE_THRESHOLD_9				(SMTCFG_TAG_WRITE	+ (26	<< 8) + 12)
#define SMTCFG_AFN_GET_SAMPLE_THRESHOLD_9				(SMTCFG_TAG_READ	+ (26	<< 8) + 12)

//page13:ads校准值
#define SMTCFG_AFN_SET_AD_CAL_VAL_0				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 0)
#define SMTCFG_AFN_GET_AD_CAL_VAL_0				(SMTCFG_TAG_READ	+ (13	<< 8) + 0)
#define SMTCFG_AFN_SET_AD_CAL_VAL_1				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 1)
#define SMTCFG_AFN_GET_AD_CAL_VAL_1				(SMTCFG_TAG_READ	+ (13	<< 8) + 1)
#define SMTCFG_AFN_SET_AD_CAL_VAL_2				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 2)
#define SMTCFG_AFN_GET_AD_CAL_VAL_2				(SMTCFG_TAG_READ	+ (13	<< 8) + 2)
#define SMTCFG_AFN_SET_AD_CAL_VAL_3				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 3)
#define SMTCFG_AFN_GET_AD_CAL_VAL_3				(SMTCFG_TAG_READ	+ (13	<< 8) + 3)
#define SMTCFG_AFN_SET_AD_CAL_VAL_4				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 4)
#define SMTCFG_AFN_GET_AD_CAL_VAL_4				(SMTCFG_TAG_READ	+ (13	<< 8) + 4)
#define SMTCFG_AFN_SET_AD_CAL_VAL_5				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 5)
#define SMTCFG_AFN_GET_AD_CAL_VAL_5				(SMTCFG_TAG_READ	+ (13	<< 8) + 5)
#define SMTCFG_AFN_SET_AD_CAL_VAL_6				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 6)
#define SMTCFG_AFN_GET_AD_CAL_VAL_6				(SMTCFG_TAG_READ	+ (13	<< 8) + 6)
#define SMTCFG_AFN_SET_AD_CAL_VAL_7				(SMTCFG_TAG_WRITE	+ (13	<< 8) + 7)
#define SMTCFG_AFN_GET_AD_CAL_VAL_7				(SMTCFG_TAG_READ	+ (13	<< 8) + 7)
#define SMTCFG_AFN_GET_AD_VAL_0					(SMTCFG_TAG_READ	+ (13	<< 8) + 8)
#define SMTCFG_AFN_GET_AD_VAL_1					(SMTCFG_TAG_READ	+ (13	<< 8) + 9)
#define SMTCFG_AFN_GET_AD_VAL_2					(SMTCFG_TAG_READ	+ (13	<< 8) + 10)
#define SMTCFG_AFN_GET_AD_VAL_3					(SMTCFG_TAG_READ	+ (13	<< 8) + 11)
#define SMTCFG_AFN_GET_AD_VAL_4					(SMTCFG_TAG_READ	+ (13	<< 8) + 12)
#define SMTCFG_AFN_GET_AD_VAL_5					(SMTCFG_TAG_READ	+ (13	<< 8) + 13)
#define SMTCFG_AFN_GET_AD_VAL_6					(SMTCFG_TAG_READ	+ (13	<< 8) + 14)
#define SMTCFG_AFN_GET_AD_VAL_7					(SMTCFG_TAG_READ	+ (13	<< 8) + 15)

//page15:实时数据
#define SMTCFG_AFN_GET_SAMPLE_WUSHUI			(SMTCFG_TAG_READ	+ (15	<< 8) + 0)
#define SMTCFG_AFN_GET_SAMPLE_COD				(SMTCFG_TAG_READ	+ (15	<< 8) + 1)

//page16:SL651
#define SMTCFG_AFN_SET_SL651_RTU_ADDR			(SMTCFG_TAG_WRITE	+ (16	<< 8) + 0)
#define SMTCFG_AFN_GET_SL651_RTU_ADDR			(SMTCFG_TAG_READ	+ (16	<< 8) + 0)
#define SMTCFG_AFN_SET_SL651_PW					(SMTCFG_TAG_WRITE	+ (16	<< 8) + 1)
#define SMTCFG_AFN_GET_SL651_PW					(SMTCFG_TAG_READ	+ (16	<< 8) + 1)
#define SMTCFG_AFN_SET_SL651_SN					(SMTCFG_TAG_WRITE	+ (16	<< 8) + 2)
#define SMTCFG_AFN_GET_SL651_SN					(SMTCFG_TAG_READ	+ (16	<< 8) + 2)
#define SMTCFG_AFN_SET_SL651_RTU_TYPE			(SMTCFG_TAG_WRITE	+ (16	<< 8) + 3)
#define SMTCFG_AFN_GET_SL651_RTU_TYPE			(SMTCFG_TAG_READ	+ (16	<< 8) + 3)
#define SMTCFG_AFN_SET_SL651_REPORT_HOUR		(SMTCFG_TAG_WRITE	+ (16	<< 8) + 4)
#define SMTCFG_AFN_GET_SL651_REPORT_HOUR		(SMTCFG_TAG_READ	+ (16	<< 8) + 4)
#define SMTCFG_AFN_SET_SL651_REPORT_MIN			(SMTCFG_TAG_WRITE	+ (16	<< 8) + 5)
#define SMTCFG_AFN_GET_SL651_REPORT_MIN			(SMTCFG_TAG_READ	+ (16	<< 8) + 5)
#define SMTCFG_AFN_SET_SL651_RANDOM_PERIOD		(SMTCFG_TAG_WRITE	+ (16	<< 8) + 6)
#define SMTCFG_AFN_GET_SL651_RANDOM_PERIOD		(SMTCFG_TAG_READ	+ (16	<< 8) + 6)

//page12:HJ212
#define SMTCFG_AFN_SET_HJ212_ST					(SMTCFG_TAG_WRITE	+ (12	<< 8) + 0)
#define SMTCFG_AFN_GET_HJ212_ST					(SMTCFG_TAG_READ	+ (12	<< 8) + 0)
#define SMTCFG_AFN_SET_HJ212_PW					(SMTCFG_TAG_WRITE	+ (12	<< 8) + 1)
#define SMTCFG_AFN_GET_HJ212_PW					(SMTCFG_TAG_READ	+ (12	<< 8) + 1)
#define SMTCFG_AFN_SET_HJ212_MN					(SMTCFG_TAG_WRITE	+ (12	<< 8) + 2)
#define SMTCFG_AFN_GET_HJ212_MN					(SMTCFG_TAG_READ	+ (12	<< 8) + 2)
#define SMTCFG_AFN_SET_HJ212_OVER_TIME			(SMTCFG_TAG_WRITE	+ (12	<< 8) + 3)
#define SMTCFG_AFN_GET_HJ212_OVER_TIME			(SMTCFG_TAG_READ	+ (12	<< 8) + 3)
#define SMTCFG_AFN_SET_HJ212_RECOUNT			(SMTCFG_TAG_WRITE	+ (12	<< 8) + 4)
#define SMTCFG_AFN_GET_HJ212_RECOUNT			(SMTCFG_TAG_READ	+ (12	<< 8) + 4)
#define SMTCFG_AFN_SET_HJ212_RTD_EN				(SMTCFG_TAG_WRITE	+ (12	<< 8) + 5)
#define SMTCFG_AFN_GET_HJ212_RTD_EN				(SMTCFG_TAG_READ	+ (12	<< 8) + 5)
#define SMTCFG_AFN_SET_HJ212_RTD_INTERVAL		(SMTCFG_TAG_WRITE	+ (12	<< 8) + 6)
#define SMTCFG_AFN_GET_HJ212_RTD_INTERVAL		(SMTCFG_TAG_READ	+ (12	<< 8) + 6)
#define SMTCFG_AFN_SET_HJ212_MIN_INTERVAL		(SMTCFG_TAG_WRITE	+ (12	<< 8) + 7)
#define SMTCFG_AFN_GET_HJ212_MIN_INTERVAL		(SMTCFG_TAG_READ	+ (12	<< 8) + 7)
#define SMTCFG_AFN_SET_HJ212_TIME_CALI_REQ		(SMTCFG_TAG_WRITE	+ (12	<< 8) + 8)
#define SMTCFG_AFN_SET_HJ212_RS_EN				(SMTCFG_TAG_WRITE	+ (12	<< 8) + 9)
#define SMTCFG_AFN_GET_HJ212_RS_EN				(SMTCFG_TAG_READ	+ (12	<< 8) + 9)



rt_uint8_t smtcfg_data_decoder(PTCL_REPORT_DATA *report_data_ptr, PTCL_RECV_DATA const *recv_data_ptr, PTCL_PARAM_INFO **param_info_ptr_ptr);



#endif

